spring:
  profiles:
    active: dev

  flyway:
    schemas: cardapi
    enabled: true
    baselineOnMigrate: false
  jpa:
    # uncomment to create initial migration for flyway and disable spring.flyway.enabled with false value
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#
#            scripts:
#              action: create
#              create-target: src/main/resources/db/whole_database.sql

    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    username: root # of course this shouldn't be part of the commit
    password: root # of course this shouldn't be part of the commit
    url: jdbc:mysql://localhost:3306/cardapi?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8 #local

apiKey: 7796f5e80525ea1677f134fbbcfb20ee2aaa9e38 # of course this shouldn't be part of the commit